+ source scripts/common.sh
+ source scripts/config.sh
++ export CLUSTER_NAME=sb-03-09-osdgcp
++ CLUSTER_NAME=sb-03-09-osdgcp
++ export MAIN_IMAGE_TAG=3.68.0
++ MAIN_IMAGE_TAG=3.68.0
++ export KUBECONFIG=/tmp/kubeconfig
++ KUBECONFIG=/tmp/kubeconfig
++ export STACKROX_SOURCE_ROOT=/Users/shane/go/src/github.com/stackrox/stackrox
++ STACKROX_SOURCE_ROOT=/Users/shane/go/src/github.com/stackrox/stackrox
++ export WORKFLOW_SOURCE_ROOT=/Users/shane/go/src/github.com/stackrox/workflow
++ WORKFLOW_SOURCE_ROOT=/Users/shane/go/src/github.com/stackrox/workflow
++ export STACKROX_TEARDOWN_SCRIPT=/Users/shane/go/src/github.com/stackrox/workflow/bin/teardown
++ STACKROX_TEARDOWN_SCRIPT=/Users/shane/go/src/github.com/stackrox/workflow/bin/teardown
++ export STACKROX_NAMESPACE=stackrox
++ STACKROX_NAMESPACE=stackrox
++ export CENTRAL_BUNDLE_DPATH=/tmp/central-bundle
++ CENTRAL_BUNDLE_DPATH=/tmp/central-bundle
++ export QA_TESTS_BACKEND_DIR=/Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend
++ QA_TESTS_BACKEND_DIR=/Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend
+ cd /Users/shane/go/src/github.com/stackrox/stackrox
+++ dirname ./scripts/step3-run-qa-tests-backend.sh
++ realpath ./scripts
+ SCRIPT_ROOT=/Users/shane/go/src/github.com/stackrox/stackrox/scripts
+ echo 'SCRIPT_ROOT          : /Users/shane/go/src/github.com/stackrox/stackrox/scripts'
SCRIPT_ROOT          : /Users/shane/go/src/github.com/stackrox/stackrox/scripts
+ echo 'QA_TESTS_BACKEND_DIR : /Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend'
QA_TESTS_BACKEND_DIR : /Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend
+ echo 'Creating /Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend/qa-test-settings.properties'
Creating /Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend/qa-test-settings.properties
+ pass show qa-test-settings.properties
+ cd /Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend
++ pass quay-io-ro-username
+ REGISTRY_USERNAME=cgorman1+stackroxuserro
+ export REGISTRY_USERNAME
++ pass quay-io-ro-password
+ REGISTRY_PASSWORD=2BHSDJ8MFE7DNKTLMY8P30LKCBEXAZYB3P3NAKRPF3BUSFCU5R3PZ57051I3R9FZ
+ export REGISTRY_PASSWORD
+ false
+ echo 'SKIPPING BUILD TO SPEEDUP DEV LOOP'
SKIPPING BUILD TO SPEEDUP DEV LOOP
+ export CLUSTER=OPENSHIFT
+ CLUSTER=OPENSHIFT
+ export AWS_ECR_REGISTRY_NAME=051999192406
+ AWS_ECR_REGISTRY_NAME=051999192406
+ export AWS_ECR_REGISTRY_REGION=us-east-2
+ AWS_ECR_REGISTRY_REGION=us-east-2
++ aws ecr get-login-password
+ AWS_ECR_DOCKER_PULL_PASSWORD=eyJwYXlsb2FkIjoiSVVOaEtXS05vRjQrZEJSVkNGYmpBazN3U09wbExEbGR3N2EvQ0dvK3dYMW5DdmpMUDJpSzBJdzZxZ2xIbjN5a3A0dFpjbmdEMjZQekxUL0VvSURFUXV5YkNScjdmazJiR1NHUmM5Wk8wT1JpUlhvbTVoUHpIM2R4VnBpYldFV0VpbXd5cisyVHJsa3lLQlJjTDhDVDAvV01uRDdqMGRlRUg0b0pxS3BvN2IxZU1TOHNkM2xBNDh6ZmRGanhWZUFIK2NOcGd2dndpL1Z3V2ZKUkl3cDUvS09JM1hIbTJmWnorN1M0bWcrVmNuRHNFY1hOaENpYkY4cG1SZ3FNZ2VhMnR3a0U3YlcxM3lEYTNXeFN2YWpPS2c5YjEwelpaa0VjMWRCVE0vNktSZlBvdHNFRnV1RE5MbUl6V20wZU1DdU43R2lXS1AzSkZaWDhBdXFSVmFHaUlIQ2ZPNFU1Y2orVWViTFB6TndTZ1ZRSGlveThsVy9zK0phRFFWSEpEcmtJNGhQNzZ3cGV3QmtJZ295UzNwZWprbnhLdWJNbWdCcjcxai9wTXJPZGZpRzFtcC82QjBaQ0tlM2lueTlEK2orT3lHbW1HcjZjckxSbTUzblo3VTZ1V0hiSy93NTBIYmgwVERxTEZQMGhtQjlvSXBabXh1Z2tDa2xYeEFzWFhSZVI1VkpLR1F2WWhPOFQvcnFwNC96NEgvYTM0bEJLcTNpeElQcCtTR3Y1b3pCYytsemNiUk9KdFhqMis0YTRGZ09sOS9LTXptU0Z2S1o5cWNsMC9oRzRXc0JGckkycnNaMmJndlQ4ak5zdXVmVHQzRFFBcVo3R2IySzRGb2lRY2hqSENzeWJySDZoM0xGUHdLRGFqNFZVWmdvMGVzUmZRemhmWGt0WkxKZ0FOTWZJZnFqcVdETExzeHFOTURhOWN3U0MwbjUzeEYvTm5ZUkpuUWUrb2IvN2JMamV0ckp1dUFaakVZTkxiL2xwd3AzOHRkcmtYTFNKOUpGV21iQXk4U2RsUnExZ3JZMldCcWlsQzEyWXZEdk1zT01lb05kbzhwY2FnZDdpSENTRCs4Mzc1T1NQYnVXK1pMdklDTzJSL241bTVMb2ZFckhobDBIUmVzQmhDa09ORU90eDEvQzN5ZTZVdG1jSytLZG5OUnFLdm0rN2Q2bThvaDU2dXFDdnArOUxoSHZKMlcwS1hBc2M4dWFGeDZHdmFXOGc4ZjB4Wjd1Q0pzUTBTdERlVUtZTExGY3NMUnM3clg5RXZxbk03MTJRWUxwNVR1ekpVNWNPVDhHS1JWbkxUQWJvRlhSQkNseGJWNjVjbnp3ZU9ER2VITlFuTjhMdjErZDZOWThET2ZPNGV1aDlNWnp1RkwxdUpWUFEwUT09IiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURIWmFzSlB2MHZRVVE5UnAyUUlCRUlBNzZDVVM3ei9qbkd6MlF4MDRHZ1EzMTRMNDhtN2p5N250MThHa0RXcVMxMko2cUtvdmIvV0pkVVFHa055MjBOcTJyNHlVWWphTzBOc21nZWM9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjQ3NTk1NDI4fQ==
+ export AWS_ECR_DOCKER_PULL_PASSWORD
++ pass quay-io-ro-username
+ QUAY_USERNAME=cgorman1+stackroxuserro
++ pass quay-io-ro-password
+ QUAY_PASSWORD=2BHSDJ8MFE7DNKTLMY8P30LKCBEXAZYB3P3NAKRPF3BUSFCU5R3PZ57051I3R9FZ
+ export QUAY_USERNAME QUAY_PASSWORD
+ export KUBECONFIG=/tmp/kubeconfig
+ KUBECONFIG=/tmp/kubeconfig
+ pkill -f 'port-forward.*svc/central'
+ true
+ sleep 2
+ sleep 3
+ kubectl port-forward -n stackrox svc/central 8000:443
+ export API_HOSTNAME=localhost
+ API_HOSTNAME=localhost
+ export API_PORT=8000
+ API_PORT=8000
+ nc -vz localhost 8000
Connection to localhost port 8000 [tcp/irdmi] succeeded!
+ PASSWORD_FILE_PATH=/Users/shane/go/src/github.com/stackrox/stackrox/deploy/openshift/central-deploy/password
+ ROX_USERNAME=admin
++ cat /Users/shane/go/src/github.com/stackrox/stackrox/deploy/openshift/central-deploy/password
+ ROX_PASSWORD=jTuf2hA21M9haKd8CgZKNwSU2
+ export ROX_USERNAME ROX_PASSWORD
+ echo 'Access Central console at localhost:8000'
Access Central console at localhost:8000
+ echo 'Login with (admin, jTuf2hA21M9haKd8CgZKNwSU2)'
Login with (admin, jTuf2hA21M9haKd8CgZKNwSU2)
+ gradle test --tests=ImageScanningTest
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :compileGroovy UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :extractIncludeTestProto UP-TO-DATE
> Task :extractTestProto UP-TO-DATE
> Task :generateTestProto NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :compileTestGroovy UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/shane/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.18/c7f02fbefc94a427f8a7109145e3ff16d5a03df9/groovy-all-2.4.18.jar) to method java.net.URL.toLowerCase(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

ImageScanningTest STANDARD_OUT
    [PATH:/usr/local/bin:/Users/shane/.cargo/bin:/Users/shane/go/bin:/usr/local/go/bin:/Users/shane/Downloads/google-cloud-sdk/bin:/Users/shane/Dowloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/munki:/Library/Apple/usr/bin:/Users/shane/miniconda3/bin:/Users/shane/miniconda3/condabin:/Users/shane/Downloads/google-cloud-sdk/bin:/Users/shane/Dowloads/google-cloud-sdk/bin:/Users/shane/go/bin:/Users/shane/.cargo/bin, QUAY_PASSWORD:2BHSDJ8MFE7DNKTLMY8P30LKCBEXAZYB3P3NAKRPF3BUSFCU5R3PZ57051I3R9FZ, WORKFLOW_SOURCE_ROOT:/Users/shane/go/src/github.com/stackrox/workflow, LC_TERMINAL:iTerm2, KUBECONFIG:/tmp/kubeconfig, CONDA_DEFAULT_ENV:base, CONDA_PYTHON_EXE:/Users/shane/miniconda3/bin/python, INPUTRC:~/.inputrc, KCTX_PROD2_STACKROX_IO:gke_stackrox-hub_us-west3_prod2-stackrox-io, REGISTRY_USERNAME:cgorman1+stackroxuserro, KCTX_PROD1_STACKROX_IO:gke_stackrox-hub_us-west2_prod1-stackrox-io, CONDA_PREFIX:/Users/shane/miniconda3, STACKROX_NAMESPACE:stackrox, CLOUDSDK_PYTHON:/usr/local/bin/python3, WINEDITOR:vim, MAIN_IMAGE_TAG:3.68.0, COLORTERM:truecolor, STACKROX_TEARDOWN_SCRIPT:/Users/shane/go/src/github.com/stackrox/workflow/bin/teardown, CENTRAL_BUNDLE_DPATH:/tmp/central-bundle, KCTX_INFRA_PRODUCTION:gke_stackrox-infra_us-west2_infra-production, LOGNAME:shane, KEYTIMEOUT:1, CLUSTER:OPENSHIFT, PWD:/Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend, TERM_PROGRAM_VERSION:3.2a, TEST_ARTIFACTS_DIR:/Users/shane/artifacts/test, AWS_ECR_DOCKER_PULL_PASSWORD:eyJwYXlsb2FkIjoiSVVOaEtXS05vRjQrZEJSVkNGYmpBazN3U09wbExEbGR3N2EvQ0dvK3dYMW5DdmpMUDJpSzBJdzZxZ2xIbjN5a3A0dFpjbmdEMjZQekxUL0VvSURFUXV5YkNScjdmazJiR1NHUmM5Wk8wT1JpUlhvbTVoUHpIM2R4VnBpYldFV0VpbXd5cisyVHJsa3lLQlJjTDhDVDAvV01uRDdqMGRlRUg0b0pxS3BvN2IxZU1TOHNkM2xBNDh6ZmRGanhWZUFIK2NOcGd2dndpL1Z3V2ZKUkl3cDUvS09JM1hIbTJmWnorN1M0bWcrVmNuRHNFY1hOaENpYkY4cG1SZ3FNZ2VhMnR3a0U3YlcxM3lEYTNXeFN2YWpPS2c5YjEwelpaa0VjMWRCVE0vNktSZlBvdHNFRnV1RE5MbUl6V20wZU1DdU43R2lXS1AzSkZaWDhBdXFSVmFHaUlIQ2ZPNFU1Y2orVWViTFB6TndTZ1ZRSGlveThsVy9zK0phRFFWSEpEcmtJNGhQNzZ3cGV3QmtJZ295UzNwZWprbnhLdWJNbWdCcjcxai9wTXJPZGZpRzFtcC82QjBaQ0tlM2lueTlEK2orT3lHbW1HcjZjckxSbTUzblo3VTZ1V0hiSy93NTBIYmgwVERxTEZQMGhtQjlvSXBabXh1Z2tDa2xYeEFzWFhSZVI1VkpLR1F2WWhPOFQvcnFwNC96NEgvYTM0bEJLcTNpeElQcCtTR3Y1b3pCYytsemNiUk9KdFhqMis0YTRGZ09sOS9LTXptU0Z2S1o5cWNsMC9oRzRXc0JGckkycnNaMmJndlQ4ak5zdXVmVHQzRFFBcVo3R2IySzRGb2lRY2hqSENzeWJySDZoM0xGUHdLRGFqNFZVWmdvMGVzUmZRemhmWGt0WkxKZ0FOTWZJZnFqcVdETExzeHFOTURhOWN3U0MwbjUzeEYvTm5ZUkpuUWUrb2IvN2JMamV0ckp1dUFaakVZTkxiL2xwd3AzOHRkcmtYTFNKOUpGV21iQXk4U2RsUnExZ3JZMldCcWlsQzEyWXZEdk1zT01lb05kbzhwY2FnZDdpSENTRCs4Mzc1T1NQYnVXK1pMdklDTzJSL241bTVMb2ZFckhobDBIUmVzQmhDa09ORU90eDEvQzN5ZTZVdG1jSytLZG5OUnFLdm0rN2Q2bThvaDU2dXFDdnArOUxoSHZKMlcwS1hBc2M4dWFGeDZHdmFXOGc4ZjB4Wjd1Q0pzUTBTdERlVUtZTExGY3NMUnM3clg5RXZxbk03MTJRWUxwNVR1ekpVNWNPVDhHS1JWbkxUQWJvRlhSQkNseGJWNjVjbnp3ZU9ER2VITlFuTjhMdjErZDZOWThET2ZPNGV1aDlNWnp1RkwxdUpWUFEwUT09IiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURIWmFzSlB2MHZRVVE5UnAyUUlCRUlBNzZDVVM3ei9qbkd6MlF4MDRHZ1EzMTRMNDhtN2p5N250MThHa0RXcVMxMko2cUtvdmIvV0pkVVFHa055MjBOcTJyNHlVWWphTzBOc21nZWM9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjQ3NTk1NDI4fQ==, SHELL:/bin/zsh, REGISTRY_PASSWORD:2BHSDJ8MFE7DNKTLMY8P30LKCBEXAZYB3P3NAKRPF3BUSFCU5R3PZ57051I3R9FZ, GOPATH:/Users/shane/go, AWS_ECR_REGISTRY_REGION:us-east-2, VISUAL:vim, ITERM_PROFILE:Default, TMPDIR:/var/folders/gq/6n39mxbd0jjdjtcd9htb3rvh0000gp/T/, XPC_FLAGS:0x0, TERM_SESSION_ID:w0t0p0:DD37DC67-96CA-415A-99D4-C725493453D1, API_PORT:8000, ROX_USERNAME:admin, __CF_USER_TEXT_ENCODING:0x1F6:0x0:0x0, INFRA_ARTIFACTS_DIR:/Users/shane/artifacts/infra, CONDA_PROMPT_MODIFIER:(base) , COLORFGBG:7;0, SHLVL:3, TMUX_PANE:%139, PYTHONPYCACHEPREFIX:/tmp/__pycache__, IGNOREEOF:2, CONDA_EXE:/Users/shane/miniconda3/bin/conda, JAVA_HOME:/Users/shane/Library/Java/JavaVirtualMachines/openjdk-15.0.1/Contents/Home, TERM:xterm-256color, STACKROX_SOURCE_ROOT:/Users/shane/go/src/github.com/stackrox/stackrox, LANG:en_US.UTF-8, COMMAND_MODE:unix2003, ROX_PASSWORD:jTuf2hA21M9haKd8CgZKNwSU2, _CE_M:, ITERM_SESSION_ID:w0t0p0:DD37DC67-96CA-415A-99D4-C725493453D1, JAVA_MAIN_CLASS_69890:worker.org.gradle.process.internal.worker.GradleWorkerMain, XPC_SERVICE_NAME:0, CONDA_SHLVL:1, __CFBundleIdentifier:com.googlecode.iterm2, LC_TERMINAL_VERSION:3.4.3, CLUSTER_NAME:sb-03-09-osdgcp, TERM_PROGRAM:tmux, QUAY_USERNAME:cgorman1+stackroxuserro, KCTX_INFRA_DEVELOPMENT:gke_stackrox-infra_us-west2_infra-development, LSCOLORS:Hxfxcxdxbxegedabagacad, HOMEBREW_NO_AUTO_UPDATE:1, API_HOSTNAME:localhost, AWS_ECR_REGISTRY_NAME:051999192406, GPG_TTY:/dev/ttys002, JAVA_MAIN_CLASS_69879:org.gradle.launcher.GradleMain, USER:shane, SSH_AUTH_SOCK:/private/tmp/com.apple.launchd.264AaNcHgO/Listeners, _CE_CONDA:, EDITOR:vim, KCTX_STAGING_STACKROX_IO:gke_stackrox-hub-staging_us-central1_staging-stackrox-io, AWS_VAULT_BACKEND:keychain, TMUX:/private/tmp/tmux-502/default,10986,0, QA_TESTS_BACKEND_DIR:/Users/shane/go/src/github.com/stackrox/stackrox/qa-tests-backend, HOME:/Users/shane]
    2022-03-17 14:24:05 Starting testsuite
    Performing global setup
    Will perform strict integration testing (if any is required)
    quay: secret created.
    public-dockerhub: secret created.
    gcr-image-pull-secret: secret created.
    Testing against:
    version: "3.68.0"
    build_flavor: "release"
    release_build: true
    license_status: VALID

    isGKE: false
    isEKS: false
    isOpenShift3: false
    isOpenShift4: true
    Unable to enable the authz plugin, defaulting to basic auth: INVALID_ARGUMENT: could not contact authorization plugin: Post "https://authorization-plugin.stackrox:443/authorize": dial tcp: lookup authorization-plugin.stackrox on 172.30.0.10:53: no such host
    Check the central logs for full error.: invalid arguments
    No Stackrox scanner integrations were found
    gcr-image-pull-secret: Secret removed.
    Image integration deleted: 2e26311f-b665-46d3-be14-5bfeb5f9b799

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-keep-autogenerated STANDARD_OUT
    2022-03-17 14:24:20 Starting testcase
    gcr-image-scanning-test: secret created.
    Caught exception: Condition not satisfied:

    autoGenerated
    |
    null
    . Retrying in 2s
    Caught exception: Condition not satisfied:

    autoGenerated
    |
    null
    . Retrying in 2s
    Caught exception: Condition not satisfied:

    autoGenerated
    |
    null
    . Retrying in 2s
    Caught exception: Condition not satisfied:

    autoGenerated
    |
    null
    . Retrying in 2s
    Caught exception: Condition not satisfied:

    autoGenerated
    |
    null
    . Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    autoGenerated
    |
    null

    Test Failed... Attempting Retry #1
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Told the orchestrator to createOrReplace gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=[rpc error: code = Unknown desc = Requesting bear token: invalid status code from registry 400 (Bad Request), rpc error: code = Unknown desc = reading manifest 0.3 in us.gcr.io/stackrox-ci/qa/registry-image: denied: Permission denied for "0.3" from request "/v2/stackrox-ci/qa/registry-image/manifests/0.3". ], reason=ErrImagePull, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    	- gcr-keep-autogenerated--gcr-image-scanning-test-779769456-h6794
    	  Container status: ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=Back-off pulling image "us.gcr.io/stackrox-ci/qa/registry-image:0.3", reason=ImagePullBackOff, additionalProperties={}), additionalProperties={})
    null/1 are in the ready state for gcr-keep-autogenerated--gcr-image-scanning-test
    Waiting for gcr-keep-autogenerated--gcr-image-scanning-test to start
    Error getting k8s deploymentio.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Deployment]  with name: [gcr-keep-autogenerated--gcr-image-scanning-test]  in namespace: [qa]  failed.
    Status of gcr-keep-autogenerated--gcr-image-scanning-test's pods:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [qa]  failed.. Retrying in 3s
    Error while waiting for deployment/populating deployment info: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [qa]  failed.
    An exception occurred which will cause a retry: orchestratormanager.OrchestratorManagerException: The deployment did not start or reach replica ready state
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Won't collect logs when not in CI
    2022-03-17 14:27:04 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-keep-autogenerated FAILED
    io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
        at app//io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:539)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:452)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy:1080)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//orchestratormanager.Kubernetes.deleteSecret(Kubernetes.groovy:1079)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:149)

        Caused by:
        java.net.SocketTimeoutException: Connect timed out
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:536)
            ... 11 more

    io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
        at app//io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:539)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:452)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy:1080)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//orchestratormanager.Kubernetes.deleteSecret(Kubernetes.groovy:1079)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:149)

        Caused by:
        java.net.SocketTimeoutException: Connect timed out
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:536)
            ... 11 more

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr STANDARD_OUT
    2022-03-17 14:27:04 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    Test Failed... Attempting Retry #1
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    An exception occurred which will cause a retry: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Won't collect logs when not in CI
    2022-03-17 14:29:02 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr FAILED
    io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
        at app//io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:539)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:452)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy:1080)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//orchestratormanager.Kubernetes.deleteSecret(Kubernetes.groovy:1079)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:149)

        Caused by:
        java.net.SocketTimeoutException: Connect timed out
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:536)
            ... 11 more

    io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
        at app//io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:539)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:452)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy:1080)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//orchestratormanager.Kubernetes.deleteSecret(Kubernetes.groovy:1079)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:149)

        Caused by:
        java.net.SocketTimeoutException: Connect timed out
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:536)
            ... 10 more

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-fully-qualified-endpoint STANDARD_OUT
    2022-03-17 14:29:02 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    Test Failed... Attempting Retry #1
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    An exception occurred which will cause a retry: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Post test cleanup:
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    Caught exception: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.. Retrying in 3s
    gcr-image-scanning-test: Secret removed.
    2022-03-17 14:31:05 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-fully-qualified-endpoint FAILED
    io.fabric8.kubernetes.client.KubernetesClientException: Operation: [delete]  for kind: [Secret]  with name: [gcr-image-scanning-test]  in namespace: [qa]  failed.
        at app//io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:130)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:539)
        at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:452)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy:1080)
        at orchestratormanager.Kubernetes.deleteSecret_closure25(Kubernetes.groovy)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//orchestratormanager.Kubernetes.deleteSecret(Kubernetes.groovy:1079)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:149)

        Caused by:
        java.net.SocketTimeoutException: Connect timed out
            at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
            at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
            at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
            at java.base/java.net.Socket.connect(Socket.java:648)
            at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
            at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
            at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
            at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
            at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:38)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:309)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
            at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:536)
            ... 9 more

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-duplicate STANDARD_OUT
    2022-03-17 14:31:05 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    2022-03-17 14:31:51 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-duplicate FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageIntegrationServiceGrpc$ImageIntegrationServiceBlockingStub.getImageIntegrations(ImageIntegrationServiceGrpc.java:601)
        at app//services.ImageIntegrationService.getImageIntegrations(ImageIntegrationService.groovy:113)
        at app//services.ImageIntegrationService.getImageIntegrationByName(ImageIntegrationService.groovy:118)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy:706)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//ImageScanningTest.expectAutoGeneratedRegistry(ImageScanningTest.groovy:703)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.Verify Image Registry+Scanner Integrations: #testName(ImageScanningTest.groovy:190)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-dupe-invalid STANDARD_OUT
    2022-03-17 14:31:51 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    2022-03-17 14:32:37 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-dupe-invalid FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageIntegrationServiceGrpc$ImageIntegrationServiceBlockingStub.getImageIntegrations(ImageIntegrationServiceGrpc.java:601)
        at app//services.ImageIntegrationService.getImageIntegrations(ImageIntegrationService.groovy:113)
        at app//services.ImageIntegrationService.getImageIntegrationByName(ImageIntegrationService.groovy:118)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy:706)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//ImageScanningTest.expectAutoGeneratedRegistry(ImageScanningTest.groovy:703)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.Verify Image Registry+Scanner Integrations: #testName(ImageScanningTest.groovy:190)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-and-other STANDARD_OUT
    2022-03-17 14:32:37 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    2022-03-17 14:33:23 Ending testcase

ImageScanningTest > Verify Image Registry+Scanner Integrations: gcr-and-other FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageIntegrationServiceGrpc$ImageIntegrationServiceBlockingStub.getImageIntegrations(ImageIntegrationServiceGrpc.java:601)
        at app//services.ImageIntegrationService.getImageIntegrations(ImageIntegrationService.groovy:113)
        at app//services.ImageIntegrationService.getImageIntegrationByName(ImageIntegrationService.groovy:118)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy:706)
        at ImageScanningTest.expectAutoGeneratedRegistry_closure2(ImageScanningTest.groovy)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//util.Helpers.evaluateWithRetry(Helpers.groovy:25)
        at app//util.Helpers.withRetry(Helpers.groovy:29)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//ImageScanningTest.expectAutoGeneratedRegistry(ImageScanningTest.groovy:703)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.Verify Image Registry+Scanner Integrations: #testName(ImageScanningTest.groovy:190)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - openssl-libs:1:1.0.1e-34.el7 - richxsl/rhel7@sha256:8f3aae325d2074d2dc328cb532d6e7aeb0c588e15ddf847347038fe0566364d6 - RHSA-2014:1052 - 1 STANDARD_OUT
    2022-03-17 14:33:23 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:34:08 Ending testcase

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - openssl-libs:1:1.0.1e-34.el7 - richxsl/rhel7@sha256:8f3aae325d2074d2dc328cb532d6e7aeb0c588e15ddf847347038fe0566364d6 - RHSA-2014:1052 - 1 FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - openssl-libs:1:1.0.1e-34.el7 - richxsl/rhel7@sha256:8f3aae325d2074d2dc328cb532d6e7aeb0c588e15ddf847347038fe0566364d6 - CVE-2014-3509 - 1 STANDARD_OUT
    2022-03-17 14:34:08 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:34:53 Ending testcase

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - openssl-libs:1:1.0.1e-34.el7 - richxsl/rhel7@sha256:8f3aae325d2074d2dc328cb532d6e7aeb0c588e15ddf847347038fe0566364d6 - CVE-2014-3509 - 1 FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - glibc:2.23-0ubuntu11.2 - quay.io/rhacs-eng/qa:oci-manifest - CVE-2015-8985 - 0 STANDARD_OUT
    2022-03-17 14:34:53 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:35:39 Ending testcase

ImageScanningTest > Verify Image Scan Results - Stackrox Scanner - glibc:2.23-0ubuntu11.2 - quay.io/rhacs-eng/qa:oci-manifest - CVE-2015-8985 - 0 FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify Image Scan Results - Anchore Scanner - openssl:1.0.1t-1+deb8u12 - us.gcr.io/stackrox-ci/qa/registry-image:0.2 - CVE-2010-0928 - 0 STANDARD_OUT
    2022-03-17 14:35:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:35:39 Ending testcase

ImageScanningTest > Verify Image Scan Results - Anchore Scanner - perl:5.20.2-3+deb8u12 - us.gcr.io/stackrox-ci/qa/registry-image:0.2 - CVE-2011-4116 - 0 STANDARD_OUT
    2022-03-17 14:35:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:35:39 Ending testcase

ImageScanningTest > Verify Image Scan Results - Clair Scanner - apt:1.4.8 - nginx:1.12.1 - CVE-2011-3374 - 0 STANDARD_OUT
    2022-03-17 14:35:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:35:39 Ending testcase

ImageScanningTest > Verify Image Scan Results - Clair Scanner - bash:4.4-5 - nginx:1.12.1 - CVE-2019-18276 - 0 STANDARD_OUT
    2022-03-17 14:35:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:35:39 Ending testcase

ImageScanningTest > Verify Scan Results from Registries - Google Artifact Registry - gcc-8:8.3.0-6 - us-west1-docker.pkg.dev/stackrox-ci/artifact-registry-test1/nginx:1.17 - CVE-2018-12886 - 0 STANDARD_OUT
    2022-03-17 14:35:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: java.lang.RuntimeException: No value assigned for required key GOOGLE_ARTIFACT_REGISTRY_SERVICE_ACCOUNT
    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:36:24 Ending testcase

ImageScanningTest > Verify Scan Results from Registries - Google Artifact Registry - gcc-8:8.3.0-6 - us-west1-docker.pkg.dev/stackrox-ci/artifact-registry-test1/nginx:1.17 - CVE-2018-12886 - 0 FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Verify image scan exceptions - Anchore Scanner - image does not exist STANDARD_OUT
    2022-03-17 14:36:24 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:36:24 Ending testcase

ImageScanningTest > Verify image scan exceptions - Clair Scanner - image does not exist STANDARD_OUT
    2022-03-17 14:36:24 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:36:24 Ending testcase

ImageScanningTest > Verify image scan exceptions - Stackrox Scanner - image does not exist STANDARD_OUT
    2022-03-17 14:36:24 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
    Test Failed... Attempting Retry #1
    Post test cleanup:
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    An exception occurred which will cause a retry: Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Post test cleanup:
    2022-03-17 14:38:39 Ending testcase

ImageScanningTest > Verify image scan exceptions - Stackrox Scanner - image does not exist FAILED
    Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
        at app//org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
        at app//org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.Verify image scan exceptions - #scanner.name() - #testAspect(ImageScanningTest.groovy:500)

        Caused by:
        Condition not satisfied:

        integrationId
        |
        ""
            at ImageScanningTest.Verify image scan exceptions - #scanner.name() - #testAspect(ImageScanningTest.groovy:489)

ImageScanningTest > Verify image scan exceptions - Anchore Scanner - missing required registry STANDARD_OUT
    2022-03-17 14:38:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:38:39 Ending testcase

ImageScanningTest > Verify image scan exceptions - Clair Scanner - missing required registry STANDARD_OUT
    2022-03-17 14:38:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:38:39 Ending testcase

ImageScanningTest > Verify image scan exceptions - Stackrox Scanner - missing required registry STANDARD_OUT
    2022-03-17 14:38:39 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
    Test Failed... Attempting Retry #1
    Post test cleanup:
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    An exception occurred which will cause a retry: Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Post test cleanup:
    2022-03-17 14:40:54 Ending testcase

ImageScanningTest > Verify image scan exceptions - Stackrox Scanner - missing required registry FAILED
    Expected exception of type 'io.grpc.StatusRuntimeException', but got 'org.spockframework.runtime.ConditionNotSatisfiedError'
        at app//org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:80)
        at app//org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:67)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at ImageScanningTest.Verify image scan exceptions - #scanner.name() - #testAspect(ImageScanningTest.groovy:500)

        Caused by:
        Condition not satisfied:

        integrationId
        |
        ""
            at ImageScanningTest.Verify image scan exceptions - #scanner.name() - #testAspect(ImageScanningTest.groovy:489)

ImageScanningTest > Image metadata from registry test - ecr-iam STANDARD_OUT
    2022-03-17 14:40:54 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    Skipping retry for: org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
    Post test cleanup:
    2022-03-17 14:40:54 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-assume-role STANDARD_OUT
    2022-03-17 14:40:54 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: java.lang.RuntimeException: No value assigned for required key AWS_ASSUME_ROLE_ACCESS_KEY_ID
    Test Failed... Attempting Retry #1
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role--ecr-image-registry-test
    ecr-assume-role--ecr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role--ecr-image-registry-test
    ecr-assume-role--ecr-image-registry-test: deployment removed.
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role--ecr-image-registry-test
    ecr-assume-role--ecr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:41:11 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-assume-role FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - ecr-assume-role-external-id STANDARD_OUT
    2022-03-17 14:41:11 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: java.lang.RuntimeException: No value assigned for required key AWS_ASSUME_ROLE_ACCESS_KEY_ID
    Test Failed... Attempting Retry #1
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role-external-id--ecr-image-registry-test
    ecr-assume-role-external-id--ecr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role-external-id--ecr-image-registry-test
    ecr-assume-role-external-id--ecr-image-registry-test: deployment removed.
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-assume-role-external-id--ecr-image-registry-test
    ecr-assume-role-external-id--ecr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:41:27 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-assume-role-external-id FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - ecr-auto STANDARD_OUT
    2022-03-17 14:41:27 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    ecr-image-registry-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto--ecr-image-registry-test
    ecr-auto--ecr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto--ecr-image-registry-test
    ecr-auto--ecr-image-registry-test: deployment removed.
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto--ecr-image-registry-test
    ecr-auto--ecr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:41:55 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-auto FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - ecr-auto-and-config STANDARD_OUT
    2022-03-17 14:41:55 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: java.lang.RuntimeException: No value assigned for required key AWS_ASSUME_ROLE_ACCESS_KEY_ID
    Test Failed... Attempting Retry #1
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto-and-config--ecr-image-registry-test
    ecr-auto-and-config--ecr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto-and-config--ecr-image-registry-test
    ecr-auto-and-config--ecr-image-registry-test: deployment removed.
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-auto-and-config--ecr-image-registry-test
    ecr-auto-and-config--ecr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:42:11 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-auto-and-config FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - ecr-config-only STANDARD_OUT
    2022-03-17 14:42:11 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: java.lang.RuntimeException: No value assigned for required key AWS_ASSUME_ROLE_ACCESS_KEY_ID
    Test Failed... Attempting Retry #1
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-config-only--ecr-image-registry-test
    ecr-config-only--ecr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-config-only--ecr-image-registry-test
    ecr-config-only--ecr-image-registry-test: deployment removed.
    Post test cleanup:
    ecr-image-registry-test: Secret removed.
    Removed the deployment: ecr-config-only--ecr-image-registry-test
    ecr-config-only--ecr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:42:28 Ending testcase

ImageScanningTest > Image metadata from registry test - ecr-config-only FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - acr-auto STANDARD_OUT
    2022-03-17 14:42:28 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    acr-image-registry-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto--acr-image-registry-test
    acr-auto--acr-image-registry-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto--acr-image-registry-test
    acr-auto--acr-image-registry-test: deployment removed.
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto--acr-image-registry-test
    acr-auto--acr-image-registry-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:42:55 Ending testcase

ImageScanningTest > Image metadata from registry test - acr-auto FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - acr-auto-and-config STANDARD_OUT
    2022-03-17 14:42:55 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed
    acr-image-registry-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto-and-config--acr-image-registry-test
    acr-auto-and-config--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto-and-config--acr-image-registry-test
    acr-auto-and-config--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-auto-and-config--acr-image-registry-test
    acr-auto-and-config--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    2022-03-17 14:44:08 Ending testcase

ImageScanningTest > Image metadata from registry test - acr-auto-and-config FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - acr-config-only STANDARD_OUT
    2022-03-17 14:44:08 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed: acr: UNAVAILABLE: io exception
    Integration test failed
    acr-image-registry-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-config-only--acr-image-registry-test
    acr-config-only--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-config-only--acr-image-registry-test
    acr-config-only--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Post test cleanup:
    acr-image-registry-test: Secret removed.
    Removed the deployment: acr-config-only--acr-image-registry-test
    acr-config-only--acr-image-registry-test: deployment removed.
    Failed to delete integration: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Won't collect logs when not in CI
    2022-03-17 14:45:20 Ending testcase

ImageScanningTest > Image metadata from registry test - acr-config-only FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - quay-auto STANDARD_OUT
    2022-03-17 14:45:20 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    quay-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    quay-image-scanning-test: Secret removed.
    Removed the deployment: quay-auto--quay-image-scanning-test
    quay-auto--quay-image-scanning-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    quay-image-scanning-test: Secret removed.
    Removed the deployment: quay-auto--quay-image-scanning-test
    quay-auto--quay-image-scanning-test: deployment removed.
    Post test cleanup:
    quay-image-scanning-test: Secret removed.
    Removed the deployment: quay-auto--quay-image-scanning-test
    quay-auto--quay-image-scanning-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:45:48 Ending testcase

ImageScanningTest > Image metadata from registry test - quay-auto FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image metadata from registry test - gcr-auto STANDARD_OUT
    2022-03-17 14:45:48 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    gcr-image-scanning-test: secret created.
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Caught exception: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Retrying in 2s
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #1
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    Removed the deployment: gcr-auto--gcr-image-scanning-test
    gcr-auto--gcr-image-scanning-test: deployment removed.
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    Removed the deployment: gcr-auto--gcr-image-scanning-test
    gcr-auto--gcr-image-scanning-test: deployment removed.
    Post test cleanup:
    gcr-image-scanning-test: Secret removed.
    Removed the deployment: gcr-auto--gcr-image-scanning-test
    gcr-auto--gcr-image-scanning-test: deployment removed.
    Won't collect logs when not in CI
    2022-03-17 14:46:15 Ending testcase

ImageScanningTest > Image metadata from registry test - gcr-auto FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image scanning test to check if scan time is not null k8s.gcr.io/ip-masq-agent-amd64:v2.4.1 from stackrox STANDARD_OUT
    2022-03-17 14:46:15 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:47:00 Ending testcase

ImageScanningTest > Image scanning test to check if scan time is not null k8s.gcr.io/ip-masq-agent-amd64:v2.4.1 from stackrox FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image scanning test to check if scan time is not null docker.io/jenkins/jenkins:lts from stackrox STANDARD_OUT
    2022-03-17 14:47:00 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:47:45 Ending testcase

ImageScanningTest > Image scanning test to check if scan time is not null docker.io/jenkins/jenkins:lts from stackrox FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image scanning test to check if scan time is not null docker.io/jenkins/jenkins:2.220-alpine from stackrox STANDARD_OUT
    2022-03-17 14:47:45 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed
    Won't collect logs when not in CI
    An exception occurred which will cause a retry: Condition not satisfied:

    integrationId
    |
    ""

    Test Failed... Attempting Retry #1
    Post test cleanup:
    An exception occurred which will cause a retry: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Test Failed... Attempting Retry #2
    Post test cleanup:
    Post test cleanup:
    Won't collect logs when not in CI
    2022-03-17 14:48:30 Ending testcase

ImageScanningTest > Image scanning test to check if scan time is not null docker.io/jenkins/jenkins:2.220-alpine from stackrox FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at app//io.stackrox.proto.api.v1.ImageServiceGrpc$ImageServiceBlockingStub.invalidateScanAndRegistryCaches(ImageServiceGrpc.java:765)
        at java.base@15.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at app//services.ImageService.clearImageCaches(ImageService.groovy:31)
        at app//ImageScanningTest.cleanup(ImageScanningTest.groovy:157)

        Caused by:
        io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8000

            Caused by:
            java.net.ConnectException: Connection refused
                at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
                at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:875)
                at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:832)

ImageScanningTest > Image scanning test to check if scan time is not null gke.gcr.io/heapster:v1.7.2 from stackrox STANDARD_OUT
    2022-03-17 14:48:30 Starting testcase
    Error getting cluster info: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
    Integration test failed: Stackrox Scanner: UNAVAILABLE: io exception
